//  ------------------------------------------------------------------------
//
//                           Q G e n   T u t o r i a l
//
//                           Simulated Data  component
//
//           Copyright (C) 2022 Universidad Politécnica de Madrid
//
//  This is free software;  you can redistribute it  and/or modify it  under
//  terms of the  GNU General Public License as published  by the Free Soft-
//  ware  Foundation;  either version 3,  or (at your option) any later ver-
//  sion.  This software is distributed in the hope  that it will be useful,
//  but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN-
//  TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
//  License for  more details.  You should have  received  a copy of the GNU
//  General  Public  License  distributed  with  this  software;   see  file
//  COPYING3.  If not, go to http://www.gnu.org/licenses for a complete copy
//  of the license.
//
//  ------------------------------------------------------------------------

#ifndef SIM_DATA_H
#define SIM_DATA_H

extern const float test_vector [5001][27];
// Gathers the autogenerated file from QGen Debugger to feed the ACS algorithm

#endif // SIM_DATA_H
